version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
  - "type: dependencies"
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
