version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '11:00'
    ignore:
      - dependency-name: '@sentry/integrations'
        versions: ['7.x']
    open-pull-requests-limit: 10
    labels:
      - 'type: dependencies'
