version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: weekly
    default_labels:
      - 'type: dependencies'
    allowed_updates:
      - match:
          update_type: all
    automerged_updates:
      - match:
          dependency_type: development
          update_type: all
      - match:
          dependency_type: production
          update_type: all
