name: misspell
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-misspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Install misspell
        run: curl -L https://git.io/misspell | bash

      - name: Run misspell
        run: bin/misspell -error .
