name: Release
on:
  push:
    branches:
      - master
jobs:
  update-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update draft
        uses: release-drafter/release-drafter@v5
        id: update-draft
    outputs:
      version: ${{ steps.update-draft.outputs.tag_name }}

  create-pr:
    runs-on: ubuntu-latest
    needs: update-draft
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update package.json
        run: |
          yarn version \
            --no-git-tag-version \
            --new-version $(echo '${{ needs.update-draft.outputs.version }}' | tr -d 'v')

      - name: Update README.md
        run: |
          sed -i -E "s/v.+\.(dmg|exe|AppImage)/$VERSION\/hackaru-desktop-$VERSION.\1/g" README.md
        env:
          VERSION: ${{ needs.update-draft.outputs.version }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ needs.update-draft.outputs.version }}
          delete-branch: true
          draft: true
          commit-message: Release ${{ needs.update-draft.outputs.version }}
          title: Release ${{ needs.update-draft.outputs.version }}
          body: ${{ needs.update-draft.outputs.body }}
          labels: |
            type: improvement
