name: release-drafter
on:
  push:
    branches:
      - master

concurrency:
  group: release-drafter
  cancel-in-progress: true

jobs:
  release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Release draft
        uses: release-drafter/release-drafter@fe52e97d262833ae07d05efaf1a239df3f1b5cd4
        id: release-draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      version: ${{ steps.release-draft.outputs.tag_name }}

  create-pr:
    runs-on: ubuntu-latest
    needs: release-draft
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Update package.json
        run: |
          yarn version \
            --no-git-tag-version \
            --new-version $(echo '${{ needs.release-draft.outputs.version }}' | tr -d 'v')

      - name: Update README.md
        run: |
          sed -i -E "s/v.+\.(dmg|exe|AppImage)/$VERSION\/hackaru-desktop-$VERSION.\1/g" README.md
        env:
          VERSION: ${{ needs.release-draft.outputs.version }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@01f7dd1d28f5131231ba3ede0f1c8cb413584a1d
        with:
          branch: ${{ needs.release-draft.outputs.version }}
          delete-branch: true
          draft: true
          commit-message: Release ${{ needs.release-draft.outputs.version }}
          title: Release ${{ needs.release-draft.outputs.version }}
          labels: |
            type: improvement
