name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run test
        run: yarn test

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
